# Generated by Django 6.0.1 on 2026-04-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businessrecord_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessrecord',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, null=True),
        ),
    ]
