# Generated by Django 6.0.1 on 2026-03-14 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_idea_validations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaScorecard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_demand', models.IntegerField(help_text='Search trends, Social signals, Existing demand', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('competition_level', models.IntegerField(help_text='Market saturation score (Higher = less saturated = better)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('profit_potential', models.IntegerField(help_text='Estimated margins vs industry benchmarks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('scalability', models.IntegerField(help_text='Can it grow without proportional cost increase ?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('entry_barriers', models.IntegerField(help_text='Technical, Regulatory, Capital Barriers (higher = low barrier = better)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('founder_fit', models.IntegerField(help_text='Skills, Experiences, Passion alignment', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('timing_factor', models.IntegerField(help_text='Market conditions fevor launch now ?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('funding_readiness', models.IntegerField(help_text='Capital requirements vs typical investor interest', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.FloatField(default=0, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='startups.ideavalidation')),
            ],
            options={
                'db_table': 'startup_idea_scorecard',
            },
        ),
        migrations.CreateModel(
            name='ProblemValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('rarely', 'Rarely')], help_text='How often does the customer face this problem ?', max_length=20)),
                ('problem_severity', models.CharField(choices=[('painkiller', 'Painkiller - must solved'), ('vitamin', 'Vitamin - nice to have')], help_text='Painkiller or Vitamin', max_length=20)),
                ('current_solution', models.TextField(help_text='What do people used today ? Spreadsheets, manual processes, competitors?')),
                ('willingness_to_pay', models.BooleanField(default=False, help_text='Are customers already paying for some solution?')),
                ('willingness_details', models.TextField(blank=True, help_text='Details on what they currently pay for')),
                ('monthly_search_volume', models.IntegerField(default=0, help_text="Estimated monthly searches for this problem's solution")),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='problem_validation', to='startups.ideavalidation')),
            ],
            options={
                'db_table': 'startup_problem_validations',
            },
        ),
        migrations.CreateModel(
            name='SolutionFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_features', models.TextField(help_text='The 20% of features delivering 80% of value - MVP core')),
                ('delight_factors', models.TextField(blank=True, help_text='Features that exceed expectations and differentiate')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, help_text='Lowest price customers indicate they would pay', max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, help_text='Highest price customers indicate they would pay', max_digits=10)),
                ('purchase_trigger', models.TextField(help_text='What specific event makes someone decide to buy ?')),
                ('commen_objections', models.TextField(blank=True, help_text='Common reasons customer give for NOT buying')),
                ('landing_page_url', models.URLField(blank=True, help_text='Smoke test landing page url if created')),
                ('waitlist_signups', models.IntegerField(default=0, help_text='Number of wait list / pre-order signup collected')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution_fit', to='startups.ideavalidation')),
            ],
            options={
                'db_table': 'startup_solution_fits',
            },
        ),
    ]
