# Generated by Django 6.0.1 on 2026-03-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemvalidation',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='solutionfit',
            name='idea',
        ),
        migrations.RenameField(
            model_name='ideavalidation',
            old_name='description',
            new_name='competition_analysis',
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='entry_barriers_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='founder_fit_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='funding_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='idea_description',
            field=models.TextField(default='', help_text='User describes their idea in plain text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='key_risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='market_demand_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='next_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='opportunities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='profit_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='raw_ai_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='scalability_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_competition',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_entry_barriers',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_founder_fit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_funding_readiness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_market_demand',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_profit_potential',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_scalability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='score_timing_factor',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='timing_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='verdict',
            field=models.CharField(blank=True, choices=[('strong_go', 'Strong GO'), ('go', 'GO'), ('caution', 'Proceed with Caution'), ('no_go', 'NO-GO'), ('pivot', 'Pivot Recommended')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ideavalidation',
            name='verdict_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ideavalidation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='IdeaScorecard',
        ),
        migrations.DeleteModel(
            name='ProblemValidation',
        ),
        migrations.DeleteModel(
            name='SolutionFit',
        ),
    ]
