# Generated by Django 6.0.1 on 2026-03-19 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_remove_problemvalidation_idea_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=100)),
                ('target_region', models.CharField(choices=[('india', 'India'), ('global', 'Global'), ('north_india', 'North India'), ('south_india', 'South India'), ('east_india', 'East India'), ('west_india', 'West India'), ('tier1_cities', 'Tier 1 Cities'), ('tier2_cities', 'Tier 2 & 3 Cities'), ('southeast_asia', 'Southeast Asia'), ('us', 'United States'), ('europe', 'Europe')], max_length=50)),
                ('customer_type', models.CharField(choices=[('b2b', 'B2B — Business to Business'), ('b2c', 'B2C — Business to Consumer'), ('both', 'Both B2B and B2C')], max_length=10)),
                ('description', models.TextField(help_text='Brief description of product and target customer')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tam_value', models.CharField(blank=True, max_length=100)),
                ('tam_explanation', models.TextField(blank=True)),
                ('sam_value', models.CharField(blank=True, max_length=100)),
                ('sam_explanation', models.TextField(blank=True)),
                ('som_value', models.CharField(blank=True, max_length=100)),
                ('som_explanation', models.TextField(blank=True)),
                ('sizing_methodology', models.TextField(blank=True)),
                ('market_growth_rate', models.CharField(blank=True, max_length=50)),
                ('market_direction', models.CharField(blank=True, max_length=20)),
                ('tailwinds', models.JSONField(blank=True, default=list)),
                ('headwinds', models.JSONField(blank=True, default=list)),
                ('tech_shifts', models.JSONField(blank=True, default=list)),
                ('regulatory_factors', models.JSONField(blank=True, default=list)),
                ('consumer_shifts', models.JSONField(blank=True, default=list)),
                ('trend_summary', models.TextField(blank=True)),
                ('personas', models.JSONField(blank=True, default=list)),
                ('key_insights', models.JSONField(blank=True, default=list)),
                ('market_summary', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_intelligence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_market_intelligence',
                'ordering': ['-created_at'],
            },
        ),
    ]
