# Generated by Django 6.0.1 on 2026-03-24 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_marketintelligence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_model', models.CharField(choices=[('subscription', 'Subscription (Monthly/Annual)'), ('one_time', 'One-time Purchase'), ('freemium', 'Freemium'), ('marketplace', 'Marketplace (Take Rate)'), ('advertising', 'Advertising'), ('usage_based', 'Usage-based / Pay per use'), ('licensing', 'Licensing'), ('not_decided', 'Not decided yet')], max_length=20)),
                ('price_per_customer', models.DecimalField(decimal_places=2, help_text='Estimated price per customer per month (₹)', max_digits=10)),
                ('estimated_cac', models.DecimalField(decimal_places=2, help_text='Estimated monthly customer acquisition cost (₹)', max_digits=10)),
                ('additional_context', models.TextField(blank=True, help_text='Any extra context — target segment, delivery method, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('canvas_problem', models.TextField(blank=True)),
                ('canvas_solution', models.TextField(blank=True)),
                ('canvas_uvp', models.TextField(blank=True)),
                ('canvas_unfair_advantage', models.TextField(blank=True)),
                ('canvas_customer_segments', models.TextField(blank=True)),
                ('canvas_channels', models.TextField(blank=True)),
                ('canvas_revenue_streams', models.TextField(blank=True)),
                ('canvas_cost_structure', models.TextField(blank=True)),
                ('canvas_key_metrics', models.TextField(blank=True)),
                ('revenue_model_analysis', models.TextField(blank=True)),
                ('revenue_model_recommended', models.CharField(blank=True, max_length=100)),
                ('revenue_model_reasoning', models.TextField(blank=True)),
                ('pricing_recommendation', models.TextField(blank=True)),
                ('ltv_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ltv_explanation', models.TextField(blank=True)),
                ('cac_analysis', models.TextField(blank=True)),
                ('ltv_cac_ratio', models.FloatField(blank=True, null=True)),
                ('ltv_cac_verdict', models.CharField(blank=True, max_length=50)),
                ('payback_period_months', models.FloatField(blank=True, null=True)),
                ('payback_verdict', models.CharField(blank=True, max_length=50)),
                ('contribution_margin', models.TextField(blank=True)),
                ('unit_economics_score', models.FloatField(blank=True, null=True)),
                ('business_model_score', models.FloatField(blank=True, null=True)),
                ('overall_verdict', models.CharField(blank=True, max_length=50)),
                ('overall_summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_models', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_business_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
