# Generated by Django 6.0.3 on 2026-03-27 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0004_businessmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MVPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('web_app', 'Web Application'), ('mobile_app', 'Mobile App'), ('both', 'Web + Mobile'), ('physical', 'Physical Product'), ('service', 'Service-based')], max_length=20)),
                ('launch_weeks', models.IntegerField(help_text='Target weeks to launch')),
                ('team_size', models.IntegerField(help_text='Number of people available to build')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('available_budget', models.CharField(blank=True, choices=[('lt_1l', 'Under ₹1 Lakh'), ('1l_5l', '₹1L – ₹5L'), ('5l_20l', '₹5L – ₹20L'), ('20l_50l', '₹20L – ₹50L'), ('gt_50l', 'Above ₹50L')], max_length=20)),
                ('tech_skills', models.CharField(blank=True, choices=[('fullstack', 'Full-stack Developer'), ('frontend', 'Frontend Only'), ('backend', 'Backend Only'), ('no_code', 'No Dev Skills — No-code only'), ('none', 'No Technical Skills')], max_length=20)),
                ('platform', models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('both', 'Web + Mobile')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mvp_score', models.FloatField(blank=True, null=True)),
                ('mvp_verdict', models.CharField(blank=True, max_length=50)),
                ('mvp_summary', models.TextField(blank=True)),
                ('core_features', models.JSONField(blank=True, default=list)),
                ('nice_to_haves', models.JSONField(blank=True, default=list)),
                ('learning_goals', models.JSONField(blank=True, default=list)),
                ('success_metrics', models.JSONField(blank=True, default=list)),
                ('mvp_risks', models.JSONField(blank=True, default=list)),
                ('total_duration_weeks', models.IntegerField(blank=True, null=True)),
                ('roadmap_summary', models.TextField(blank=True)),
                ('phases', models.JSONField(blank=True, default=list)),
                ('tech_summary', models.TextField(blank=True)),
                ('recommended_stack', models.JSONField(blank=True, default=list)),
                ('build_items', models.JSONField(blank=True, default=list)),
                ('buy_items', models.JSONField(blank=True, default=list)),
                ('nocode_options', models.JSONField(blank=True, default=list)),
                ('core_ip', models.JSONField(blank=True, default=list)),
                ('tech_recommendations', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_plans', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mvp_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_mvp_plans',
                'ordering': ['-created_at'],
            },
        ),
    ]
