# Generated by Django 6.0.3 on 2026-03-28 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0005_mvpplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_burn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('starting_monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_revenue_growth', models.FloatField(default=0, help_text='Monthly revenue growth rate in %')),
                ('current_monthly_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expense_growth_rate', models.FloatField(default=0, help_text='Monthly expense growth rate in %')),
                ('funding_amount_target', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('funds_product_pct', models.FloatField(default=40)),
                ('funds_marketing_pct', models.FloatField(default=30)),
                ('funds_salaries_pct', models.FloatField(default=20)),
                ('funds_ops_pct', models.FloatField(default=10)),
                ('funding_milestone', models.TextField(blank=True, help_text='What milestone will this funding help reach?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('runway_months', models.FloatField(blank=True, null=True)),
                ('runway_status', models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('healthy', 'Healthy'), ('raising_soon', 'Raising Soon'), ('urgent', 'Urgent'), ('critical', 'Critical')], max_length=20)),
                ('zero_date', models.CharField(blank=True, max_length=50)),
                ('runway_summary', models.TextField(blank=True)),
                ('runway_scenarios', models.JSONField(blank=True, default=list)),
                ('runway_recommendations', models.JSONField(blank=True, default=list)),
                ('breakeven_month', models.IntegerField(blank=True, null=True)),
                ('projection_summary', models.TextField(blank=True)),
                ('yearly_projections', models.JSONField(blank=True, default=list)),
                ('monthly_projections', models.JSONField(blank=True, default=list)),
                ('projection_milestones', models.JSONField(blank=True, default=list)),
                ('projection_risks', models.JSONField(blank=True, default=list)),
                ('projection_assumptions', models.JSONField(blank=True, default=list)),
                ('funding_verdict', models.CharField(blank=True, max_length=50)),
                ('funding_summary', models.TextField(blank=True)),
                ('funding_score', models.FloatField(blank=True, null=True)),
                ('valuation_context', models.TextField(blank=True)),
                ('runway_extended_months', models.FloatField(blank=True, null=True)),
                ('funding_milestones', models.JSONField(blank=True, default=list)),
                ('funding_tips', models.JSONField(blank=True, default=list)),
                ('use_of_funds_analysis', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_financials', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_financials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_financials',
                'ordering': ['-created_at'],
            },
        ),
    ]
