# Generated by Django 6.0.1 on 2026-04-01 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0006_startupfinancials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorReadiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funding_stage', models.CharField(choices=[('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A')], max_length=20)),
                ('amount_raising', models.DecimalField(decimal_places=2, max_digits=14)),
                ('team_description', models.TextField(help_text='Brief description of founding team and their backgrounds')),
                ('traction_so_far', models.TextField(help_text='Any traction — users, revenue, partnerships, pilots')),
                ('company_stage', models.CharField(choices=[('idea', 'Idea Stage'), ('mvp', 'MVP Built'), ('revenue', 'Early Revenue'), ('growth', 'Growing Revenue')], max_length=20)),
                ('completed_items', models.JSONField(blank=True, default=list, help_text='List of DD items already completed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('pitch_score', models.FloatField(blank=True, null=True)),
                ('pitch_verdict', models.CharField(blank=True, max_length=50)),
                ('pitch_summary', models.TextField(blank=True)),
                ('pitch_slides', models.JSONField(blank=True, default=list)),
                ('investor_questions', models.JSONField(blank=True, default=list)),
                ('storytelling_tips', models.JSONField(blank=True, default=list)),
                ('investor_list', models.JSONField(blank=True, default=list)),
                ('outreach_template', models.TextField(blank=True)),
                ('warm_intro_strategy', models.TextField(blank=True)),
                ('investor_tips', models.JSONField(blank=True, default=list)),
                ('dd_score', models.FloatField(blank=True, null=True)),
                ('dd_summary', models.TextField(blank=True)),
                ('dd_checklist', models.JSONField(blank=True, default=list)),
                ('dd_priority_items', models.JSONField(blank=True, default=list)),
                ('dd_red_flags', models.JSONField(blank=True, default=list)),
                ('dd_preparation_tips', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_readiness', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_readiness', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_investor_readiness',
                'ordering': ['-created_at'],
            },
        ),
    ]
