# Generated by Django 6.0.1 on 2026-04-01 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0007_investorreadiness'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoToMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beachhead_market', models.TextField(help_text='Specific segment to dominate first')),
                ('launch_weeks', models.IntegerField(help_text='Weeks from now to launch')),
                ('launch_budget', models.DecimalField(decimal_places=2, help_text='Total launch budget in ₹', max_digits=12)),
                ('monthly_acq_budget', models.DecimalField(decimal_places=2, help_text='Monthly customer acquisition budget in ₹', max_digits=12)),
                ('target_monthly_customers', models.IntegerField(help_text='Target new customers per month')),
                ('preferred_channels', models.JSONField(default=list, help_text='List of preferred acquisition channels')),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current or planned price per customer (₹)', max_digits=10)),
                ('competitor_price_min', models.DecimalField(decimal_places=2, default=0, help_text='Lowest competitor price (₹)', max_digits=10)),
                ('competitor_price_max', models.DecimalField(decimal_places=2, default=0, help_text='Highest competitor price (₹)', max_digits=10)),
                ('pricing_model', models.CharField(choices=[('subscription', 'Subscription'), ('one_time', 'One-time Purchase'), ('freemium', 'Freemium'), ('usage_based', 'Usage-based'), ('tiered', 'Tiered Pricing'), ('not_decided', 'Not decided yet')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('launch_score', models.FloatField(blank=True, null=True)),
                ('launch_verdict', models.CharField(blank=True, max_length=50)),
                ('launch_summary', models.TextField(blank=True)),
                ('beachhead_analysis', models.TextField(blank=True)),
                ('launch_channels', models.JSONField(blank=True, default=list)),
                ('first_90_days', models.JSONField(blank=True, default=list)),
                ('pr_strategy', models.TextField(blank=True)),
                ('launch_risks', models.JSONField(blank=True, default=list)),
                ('launch_tips', models.JSONField(blank=True, default=list)),
                ('acq_summary', models.TextField(blank=True)),
                ('acq_score', models.FloatField(blank=True, null=True)),
                ('channel_strategies', models.JSONField(blank=True, default=list)),
                ('budget_allocation', models.JSONField(blank=True, default=list)),
                ('growth_hacks', models.JSONField(blank=True, default=list)),
                ('channel_priority', models.JSONField(blank=True, default=list)),
                ('projected_cac', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_score', models.FloatField(blank=True, null=True)),
                ('pricing_verdict', models.CharField(blank=True, max_length=50)),
                ('pricing_summary', models.TextField(blank=True)),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pricing_rationale', models.TextField(blank=True)),
                ('package_tiers', models.JSONField(blank=True, default=list)),
                ('psychological_tips', models.JSONField(blank=True, default=list)),
                ('price_testing_plan', models.TextField(blank=True)),
                ('annual_strategy', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_to_market', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_to_market', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_go_to_market',
                'ordering': ['-created_at'],
            },
        ),
    ]
