# Generated by Django 6.0.3 on 2026-04-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0008_gotomarket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupKPIs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_model_type', models.CharField(choices=[('saas', 'SaaS / Software'), ('marketplace', 'Marketplace'), ('consumer', 'Consumer App'), ('ecommerce', 'E-commerce'), ('service', 'Service-based')], max_length=20)),
                ('primary_goal', models.CharField(choices=[('growth', 'Growth — acquire more users'), ('retention', 'Retention — keep existing users'), ('revenue', 'Revenue — maximize monetization'), ('engagement', 'Engagement — increase usage')], max_length=20)),
                ('currently_tracking', models.TextField(blank=True, help_text='Metrics the founder is currently tracking')),
                ('week1_retention', models.FloatField(default=0, help_text='% of users still active after week 1')),
                ('month1_retention', models.FloatField(default=0, help_text='% of users still active after month 1')),
                ('month3_retention', models.FloatField(default=0, help_text='% of users still active after month 3')),
                ('avg_invites_per_user', models.FloatField(default=0, help_text='Average invites sent per user')),
                ('invite_conversion_rate', models.FloatField(default=0, help_text='% of invites that convert to signups')),
                ('monthly_active_users', models.IntegerField(default=0, help_text='Current monthly active users')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('north_star_metric', models.CharField(blank=True, max_length=200)),
                ('north_star_why', models.TextField(blank=True)),
                ('north_star_how_to_measure', models.TextField(blank=True)),
                ('supporting_metrics', models.JSONField(blank=True, default=list)),
                ('kpi_benchmarks', models.JSONField(blank=True, default=list)),
                ('warning_signs', models.JSONField(blank=True, default=list)),
                ('tracking_recommendations', models.JSONField(blank=True, default=list)),
                ('retention_score', models.FloatField(blank=True, null=True)),
                ('retention_verdict', models.CharField(blank=True, max_length=50)),
                ('retention_summary', models.TextField(blank=True)),
                ('pmf_assessment', models.TextField(blank=True)),
                ('benchmark_comparison', models.JSONField(blank=True, default=list)),
                ('churn_reasons', models.JSONField(blank=True, default=list)),
                ('retention_strategies', models.JSONField(blank=True, default=list)),
                ('retention_quick_wins', models.JSONField(blank=True, default=list)),
                ('k_factor', models.FloatField(blank=True, null=True)),
                ('viral_verdict', models.CharField(blank=True, max_length=50)),
                ('viral_summary', models.TextField(blank=True)),
                ('viral_loop_design', models.TextField(blank=True)),
                ('k_factor_improvements', models.JSONField(blank=True, default=list)),
                ('growth_projections', models.JSONField(blank=True, default=list)),
                ('viral_examples', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_kpis', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_kpis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_kpis',
                'ordering': ['-created_at'],
            },
        ),
    ]
