# Generated by Django 6.0.3 on 2026-04-03 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0009_startupkpis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founders', models.JSONField(default=list, help_text='List of founders with name, role, background, equity_pct')),
                ('is_solo_founder', models.BooleanField(default=False)),
                ('current_team_size', models.IntegerField(default=1)),
                ('hiring_budget_12m', models.DecimalField(decimal_places=2, default=0, help_text='12-month hiring budget in ₹', max_digits=14)),
                ('priority_roles', models.TextField(blank=True, help_text='Roles the founder wants to hire first')),
                ('work_mode', models.CharField(choices=[('remote', 'Fully Remote'), ('office', 'In-Office'), ('hybrid', 'Hybrid')], default='hybrid', max_length=10)),
                ('current_advisors', models.TextField(blank=True, help_text='Existing advisors if any')),
                ('expertise_gaps', models.TextField(blank=True, help_text='Key areas where team lacks expertise')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('team_score', models.FloatField(blank=True, null=True)),
                ('team_verdict', models.CharField(blank=True, max_length=50)),
                ('team_summary', models.TextField(blank=True)),
                ('skills_gap_analysis', models.JSONField(blank=True, default=list)),
                ('equity_assessment', models.TextField(blank=True)),
                ('vesting_recommendation', models.TextField(blank=True)),
                ('conflict_risks', models.JSONField(blank=True, default=list)),
                ('team_recommendations', models.JSONField(blank=True, default=list)),
                ('founder_agreements', models.JSONField(blank=True, default=list)),
                ('hiring_score', models.FloatField(blank=True, null=True)),
                ('hiring_summary', models.TextField(blank=True)),
                ('hiring_roadmap', models.JSONField(blank=True, default=list)),
                ('recruitment_channels', models.JSONField(blank=True, default=list)),
                ('culture_values', models.JSONField(blank=True, default=list)),
                ('first_10_guide', models.JSONField(blank=True, default=list)),
                ('compensation_benchmarks', models.JSONField(blank=True, default=list)),
                ('hiring_mistakes', models.JSONField(blank=True, default=list)),
                ('advisory_score', models.FloatField(blank=True, null=True)),
                ('advisory_summary', models.TextField(blank=True)),
                ('ideal_advisors', models.JSONField(blank=True, default=list)),
                ('advisor_equity_guide', models.TextField(blank=True)),
                ('where_to_find', models.JSONField(blank=True, default=list)),
                ('outreach_approach', models.TextField(blank=True)),
                ('meeting_cadence', models.TextField(blank=True)),
                ('advisor_red_flags', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_culture', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_culture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_team_culture',
                'ordering': ['-created_at'],
            },
        ),
    ]
