# Generated by Django 6.0.3 on 2026-04-04 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0010_teamculture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupRisks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('b2b_saas', 'B2B SaaS'), ('b2c_app', 'B2C App'), ('marketplace', 'Marketplace'), ('service', 'Service-based'), ('physical', 'Physical Product')], max_length=20)),
                ('handles_customer_data', models.BooleanField(default=False)),
                ('handles_payments', models.BooleanField(default=False)),
                ('regulated_space', models.BooleanField(default=False)),
                ('regulation_details', models.TextField(blank=True, help_text='Which regulations apply — SEBI, RBI, FSSAI, etc.')),
                ('biggest_worry', models.TextField(blank=True, help_text="Founder's current biggest concern")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('overall_risk_score', models.FloatField(blank=True, null=True)),
                ('overall_risk_level', models.CharField(blank=True, max_length=20)),
                ('risk_summary', models.TextField(blank=True)),
                ('risk_register', models.JSONField(blank=True, default=list)),
                ('legal_summary', models.TextField(blank=True)),
                ('legal_checklist', models.JSONField(blank=True, default=list)),
                ('immediate_legal_actions', models.JSONField(blank=True, default=list)),
                ('mitigation_summary', models.TextField(blank=True)),
                ('mitigation_actions', models.JSONField(blank=True, default=list)),
                ('risk_monitoring_plan', models.JSONField(blank=True, default=list)),
                ('insurance_recommendations', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_risks', to='startups.ideavalidation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startup_risks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'startup_risks',
                'ordering': ['-created_at'],
            },
        ),
    ]
