# Generated by Django 6.0.1 on 2026-03-12 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='annual_revenue',
            field=models.CharField(blank=True, help_text='e.g., ₹1cr - ₹5cr', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('startup', 'Startup'), ('existing', 'Existing Business')], default='startup', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='custom_industry',
            field=models.CharField(blank=True, help_text="Custom industry if 'other' is selected", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='funding_stage',
            field=models.CharField(blank=True, choices=[('pre_seed', 'Pre-seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C+'), ('bootstrapped', 'Bootstrapped'), ('not_applicable', 'Not Applicable')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('ecommerce', 'E-commerce'), ('manufacturing', 'Manufacturing'), ('realestate', 'Real Estate'), ('hospitality', 'Hospitality'), ('consulting', 'Consulting'), ('retail', 'Retail'), ('construction', 'Construction'), ('transportation', 'Transportation'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='startup_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team_size',
            field=models.IntegerField(blank=True, help_text='Number of team members', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Full Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_established',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
